from collections.abc import Callable
from typing import Any, TypeVar, overload

_F = TypeVar("_F", bound=Callable[..., Any])

class Exit(SystemExit):
    def __init__(self, code: int = 0) -> None: ...

class Typer:
    def __init__(
        self, *, add_completion: bool = True, no_args_is_help: bool = False
    ) -> None: ...
    @overload
    def command(self, name: str) -> Callable[[_F], _F]: ...
    @overload
    def command(self) -> Callable[[_F], _F]: ...
    def __call__(self) -> Any: ...

def Option(*param_decls: str, **kwargs: Any) -> Any: ...
def Argument(*param_decls: str, **kwargs: Any) -> Any: ...
def run(function: Callable[..., Any]) -> Any: ...
